FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    gcc \
    g++ \
    make \
    libxml2-dev \
    libxslt-dev \
 && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip && \
    pip install setuptools_rust && \
    pip install -r requirements.txt && \
    pip install "sumy[LSA]" && \
    python -c "import nltk; nltk.download('punkt')" && \
    pip cache purge

COPY . ./

EXPOSE 8000

EXPOSE 4891

CMD ["python", "app.py"]
