version: '3'

services:
  client:
    build:
      context: ./client
    ports:
      - 3000:80

  server:
    build:
      context: ./server
    ports:
      - 5000:5000
      - 4891:4891
    volumes:
      - ./data:/app/data
    environment:
      - HOST=host.docker.internal